// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_OTK;

#nullable disable

namespace WebAPI_OTK.Migrations
{
    [DbContext(typeof(Model1))]
    [Migration("20251219115125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_OTK.sysdiagrams", b =>
                {
                    b.Property<int>("diagram_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("diagram_id"));

                    b.Property<byte[]>("definition")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("principal_id")
                        .HasColumnType("int");

                    b.Property<int?>("version")
                        .HasColumnType("int");

                    b.HasKey("diagram_id");

                    b.ToTable("sysdiagrams");
                });

            modelBuilder.Entity("WebAPI_OTK.ДСЕ", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ИзделиеID")
                        .HasColumnType("int");

                    b.Property<string>("Код")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Наименование")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Чертеж")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("ИзделиеID");

                    b.ToTable("ДСЕ");
                });

            modelBuilder.Entity("WebAPI_OTK.Должность", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Код")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Наименование")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Должность");
                });

            modelBuilder.Entity("WebAPI_OTK.Зарплата", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("ИтогоКВыплате")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ОперацияМЛID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Период")
                        .HasColumnType("date");

                    b.Property<decimal?>("Премия")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("СотрудникID")
                        .HasColumnType("int");

                    b.Property<decimal?>("СтавкаЧасовая")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("СуммаОклад")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ЧасыОтработано")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ID");

                    b.HasIndex("ОперацияМЛID");

                    b.HasIndex("СотрудникID");

                    b.ToTable("Зарплата");
                });

            modelBuilder.Entity("WebAPI_OTK.Изделие", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ДатаСоздания")
                        .HasColumnType("date");

                    b.Property<string>("Наименование")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Описание")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Состояние")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Изделие");
                });

            modelBuilder.Entity("WebAPI_OTK.МЛ", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ДСЕID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ДатаЗакрытия")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ДатаСоздания")
                        .HasColumnType("date");

                    b.Property<bool?>("Закрыт")
                        .HasColumnType("bit");

                    b.Property<int>("ИзделиеID")
                        .HasColumnType("int");

                    b.Property<int?>("КоличествоБрак")
                        .HasColumnType("int");

                    b.Property<int?>("КоличествоОТК")
                        .HasColumnType("int");

                    b.Property<string>("НомерМЛ")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("СотрудникID")
                        .HasColumnType("int");

                    b.Property<int?>("СотрудникОТК")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ДСЕID");

                    b.HasIndex("ИзделиеID");

                    b.HasIndex("СотрудникID");

                    b.HasIndex("СотрудникОТК");

                    b.ToTable("МЛ");
                });

            modelBuilder.Entity("WebAPI_OTK.Оборудование", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ДатаПоследнегоОбслуживания")
                        .HasColumnType("date");

                    b.Property<string>("ИнвентарныйНомер")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Местоположение")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Наименование")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Статус")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Оборудование");
                });

            modelBuilder.Entity("WebAPI_OTK.Операция_МЛ", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("ДатаНачала")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ДатаОкончания")
                        .HasColumnType("datetime2");

                    b.Property<int>("МЛID")
                        .HasColumnType("int");

                    b.Property<int?>("ОборудованиеID")
                        .HasColumnType("int");

                    b.Property<string>("Подразделение")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Примечание")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("СотрудникID")
                        .HasColumnType("int");

                    b.Property<string>("Статус")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ТипОперацииID")
                        .HasColumnType("int");

                    b.Property<decimal?>("ФактическаяДлительностьЧас")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ID");

                    b.HasIndex("МЛID");

                    b.HasIndex("ОборудованиеID");

                    b.HasIndex("СотрудникID");

                    b.HasIndex("ТипОперацииID");

                    b.ToTable("Операция_МЛ");
                });

            modelBuilder.Entity("WebAPI_OTK.ПремиальныеКоэффициенты", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ДСЕID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ДатаНачала")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ДатаОкончания")
                        .HasColumnType("date");

                    b.Property<int?>("ИзделиеID")
                        .HasColumnType("int");

                    b.Property<decimal>("Коэффициент")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Наименование")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ТипОперацииID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ДСЕID");

                    b.HasIndex("ИзделиеID");

                    b.HasIndex("ТипОперацииID");

                    b.ToTable("ПремиальныеКоэффициенты");
                });

            modelBuilder.Entity("WebAPI_OTK.Сотрудник", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ДатаПриема")
                        .HasColumnType("date");

                    b.Property<int?>("ДолжностьID")
                        .HasColumnType("int");

                    b.Property<string>("ТабельныйНомер")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ФИО")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("ДолжностьID");

                    b.ToTable("Сотрудник");
                });

            modelBuilder.Entity("WebAPI_OTK.ТипОперации", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("ДлительностьЧас")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("КодОперации")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Наименование")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Описание")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.ToTable("ТипОперации");
                });

            modelBuilder.Entity("WebAPI_OTK.ДСЕ", b =>
                {
                    b.HasOne("WebAPI_OTK.Изделие", "Изделие")
                        .WithMany("ДСЕ")
                        .HasForeignKey("ИзделиеID");

                    b.Navigation("Изделие");
                });

            modelBuilder.Entity("WebAPI_OTK.Зарплата", b =>
                {
                    b.HasOne("WebAPI_OTK.Операция_МЛ", "Операция_МЛ")
                        .WithMany("Зарплата")
                        .HasForeignKey("ОперацияМЛID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebAPI_OTK.Сотрудник", "Сотрудник")
                        .WithMany("Зарплата")
                        .HasForeignKey("СотрудникID");

                    b.Navigation("Операция_МЛ");

                    b.Navigation("Сотрудник");
                });

            modelBuilder.Entity("WebAPI_OTK.МЛ", b =>
                {
                    b.HasOne("WebAPI_OTK.ДСЕ", "ДСЕ")
                        .WithMany("МЛ")
                        .HasForeignKey("ДСЕID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI_OTK.Изделие", "Изделие")
                        .WithMany("МЛ")
                        .HasForeignKey("ИзделиеID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI_OTK.Сотрудник", null)
                        .WithMany("МЛ")
                        .HasForeignKey("СотрудникID");

                    b.HasOne("WebAPI_OTK.Сотрудник", "Сотрудник")
                        .WithMany()
                        .HasForeignKey("СотрудникОТК")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ДСЕ");

                    b.Navigation("Изделие");

                    b.Navigation("Сотрудник");
                });

            modelBuilder.Entity("WebAPI_OTK.Операция_МЛ", b =>
                {
                    b.HasOne("WebAPI_OTK.МЛ", "МЛ")
                        .WithMany("Операция_МЛ")
                        .HasForeignKey("МЛID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI_OTK.Оборудование", "Оборудование")
                        .WithMany("Операция_МЛ")
                        .HasForeignKey("ОборудованиеID");

                    b.HasOne("WebAPI_OTK.Сотрудник", "Сотрудник")
                        .WithMany("Операция_МЛ")
                        .HasForeignKey("СотрудникID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI_OTK.ТипОперации", "ТипОперации")
                        .WithMany("Операция_МЛ")
                        .HasForeignKey("ТипОперацииID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("МЛ");

                    b.Navigation("Оборудование");

                    b.Navigation("Сотрудник");

                    b.Navigation("ТипОперации");
                });

            modelBuilder.Entity("WebAPI_OTK.ПремиальныеКоэффициенты", b =>
                {
                    b.HasOne("WebAPI_OTK.ДСЕ", "ДСЕ")
                        .WithMany("ПремиальныеКоэффициенты")
                        .HasForeignKey("ДСЕID");

                    b.HasOne("WebAPI_OTK.Изделие", "Изделие")
                        .WithMany("ПремиальныеКоэффициенты")
                        .HasForeignKey("ИзделиеID");

                    b.HasOne("WebAPI_OTK.ТипОперации", "ТипОперации")
                        .WithMany("ПремиальныеКоэффициенты")
                        .HasForeignKey("ТипОперацииID");

                    b.Navigation("ДСЕ");

                    b.Navigation("Изделие");

                    b.Navigation("ТипОперации");
                });

            modelBuilder.Entity("WebAPI_OTK.Сотрудник", b =>
                {
                    b.HasOne("WebAPI_OTK.Должность", "Должность")
                        .WithMany("Сотрудник")
                        .HasForeignKey("ДолжностьID");

                    b.Navigation("Должность");
                });

            modelBuilder.Entity("WebAPI_OTK.ДСЕ", b =>
                {
                    b.Navigation("МЛ");

                    b.Navigation("ПремиальныеКоэффициенты");
                });

            modelBuilder.Entity("WebAPI_OTK.Должность", b =>
                {
                    b.Navigation("Сотрудник");
                });

            modelBuilder.Entity("WebAPI_OTK.Изделие", b =>
                {
                    b.Navigation("ДСЕ");

                    b.Navigation("МЛ");

                    b.Navigation("ПремиальныеКоэффициенты");
                });

            modelBuilder.Entity("WebAPI_OTK.МЛ", b =>
                {
                    b.Navigation("Операция_МЛ");
                });

            modelBuilder.Entity("WebAPI_OTK.Оборудование", b =>
                {
                    b.Navigation("Операция_МЛ");
                });

            modelBuilder.Entity("WebAPI_OTK.Операция_МЛ", b =>
                {
                    b.Navigation("Зарплата");
                });

            modelBuilder.Entity("WebAPI_OTK.Сотрудник", b =>
                {
                    b.Navigation("Зарплата");

                    b.Navigation("МЛ");

                    b.Navigation("Операция_МЛ");
                });

            modelBuilder.Entity("WebAPI_OTK.ТипОперации", b =>
                {
                    b.Navigation("Операция_МЛ");

                    b.Navigation("ПремиальныеКоэффициенты");
                });
#pragma warning restore 612, 618
        }
    }
}
